In [1]:
#Перед нами стоит задача классификации.В качестве модели используем градиентный бустинг с помощью библиотеки catboost для 
#Используем исменно данную реализацию бустинга, так как она "из коробки" способна работать с категориальными перемнными
import optuna

import numpy as np
import pandas as pd

from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.metrics import precision_score,recall_score,roc_auc_score,f1_score,confusion_matrix,classification_report

In [2]:
df = pd.read_csv('clear_train.csv')
df.head()

,Unnamed: 0,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,Female,49.0,Ludhiana,Working Professional,Chef,-1.0,5.0,-1.00,-1.0,2.0,More than 8 hours,Healthy,BHM,No,1.0,2.0,No,0
1,1,Male,26.0,Varanasi,Working Professional,Teacher,-1.0,4.0,-1.00,-1.0,3.0,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No,1
2,2,Male,33.0,Visakhapatnam,Student,Other,5.0,-1.0,8.97,2.0,-1.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
3,3,Male,22.0,Mumbai,Working Professional,Teacher,-1.0,5.0,-1.00,-1.0,1.0,Less than 5 hours,Moderate,BBA,Yes,10.0,1.0,Yes,1
4,4,Female,30.0,Kanpur,Working Professional,Business Analyst,-1.0,1.0,-1.00,-1.0,1.0,5-6 hours,Unhealthy,BBA,Yes,9.0,4.0,Yes,0

In [3]:
categorical_features = ['Gender',
                       'City',
                       'Working Professional or Student',
                       'Profession',
                       'Sleep Duration',
                       'Dietary Habits',
                       'Degree',
                       'Have you ever had suicidal thoughts ?',
                       'Family History of Mental Illness']

In [4]:
df.columns

Index(['Unnamed: 0', 'Gender', 'Age', 'City',
       'Working Professional or Student', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='object')

In [5]:
X = df.drop(['Unnamed: 0','Depression'],axis=1)
y = df['Depression']
X.head()

,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,Female,49.0,Ludhiana,Working Professional,Chef,-1.0,5.0,-1.00,-1.0,2.0,More than 8 hours,Healthy,BHM,No,1.0,2.0,No
1,Male,26.0,Varanasi,Working Professional,Teacher,-1.0,4.0,-1.00,-1.0,3.0,Less than 5 hours,Unhealthy,LLB,Yes,7.0,3.0,No
2,Male,33.0,Visakhapatnam,Student,Other,5.0,-1.0,8.97,2.0,-1.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No
3,Male,22.0,Mumbai,Working Professional,Teacher,-1.0,5.0,-1.00,-1.0,1.0,Less than 5 hours,Moderate,BBA,Yes,10.0,1.0,Yes
4,Female,30.0,Kanpur,Working Professional,Business Analyst,-1.0,1.0,-1.00,-1.0,1.0,5-6 hours,Unhealthy,BBA,Yes,9.0,4.0,Yes

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
cb_model = CatBoostClassifier()

In [16]:
cb_model.fit(X_train,y_train,cat_features=categorical_features)

Learning rate set to 0.077424
0:	learn: 0.5682297	total: 335ms	remaining: 5m 34s
1:	learn: 0.4745154	total: 493ms	remaining: 4m 5s
2:	learn: 0.4084077	total: 646ms	remaining: 3m 34s
3:	learn: 0.3551984	total: 795ms	remaining: 3m 17s
4:	learn: 0.3183929	total: 955ms	remaining: 3m 10s
5:	learn: 0.2885038	total: 1.1s	remaining: 3m 1s
6:	learn: 0.2669361	total: 1.23s	remaining: 2m 55s
7:	learn: 0.2485827	total: 1.35s	remaining: 2m 48s
8:	learn: 0.2348359	total: 1.48s	remaining: 2m 43s
9:	learn: 0.2239735	total: 1.61s	remaining: 2m 39s
10:	learn: 0.2162036	total: 1.75s	remaining: 2m 37s
11:	learn: 0.2097539	total: 1.88s	remaining: 2m 34s
12:	learn: 0.2027051	total: 2.03s	remaining: 2m 33s
13:	learn: 0.1974829	total: 2.16s	remaining: 2m 32s
14:	learn: 0.1930376	total: 2.3s	remaining: 2m 30s
15:	learn: 0.1897428	total: 2.43s	remaining: 2m 29s
16:	learn: 0.1863952	total: 2.56s	remaining: 2m 28s
17:	learn: 0.1836614	total: 2.68s	remaining: 2m 26s
18:	learn: 0.1811673	total: 2.8s	remaining: 2m 24s
19:	learn: 0.1795584	total: 2.93s	remaining: 2m 23s
20:	learn: 0.1780292	total: 3.07s	remaining: 2m 23s
21:	learn: 0.1760856	total: 3.2s	remaining: 2m 22s
22:	learn: 0.1747244	total: 3.32s	remaining: 2m 20s
23:	learn: 0.1735744	total: 3.44s	remaining: 2m 19s
24:	learn: 0.1715857	total: 3.57s	remaining: 2m 19s
25:	learn: 0.1700633	total: 3.7s	remaining: 2m 18s
26:	learn: 0.1691270	total: 3.83s	remaining: 2m 17s
27:	learn: 0.1683732	total: 3.95s	remaining: 2m 17s
28:	learn: 0.1669768	total: 4.08s	remaining: 2m 16s
29:	learn: 0.1663378	total: 4.21s	remaining: 2m 16s
30:	learn: 0.1651325	total: 4.34s	remaining: 2m 15s
31:	learn: 0.1642503	total: 4.46s	remaining: 2m 14s
32:	learn: 0.1634647	total: 4.58s	remaining: 2m 14s
33:	learn: 0.1627857	total: 4.7s	remaining: 2m 13s
34:	learn: 0.1622151	total: 4.82s	remaining: 2m 12s
35:	learn: 0.1616259	total: 4.94s	remaining: 2m 12s
36:	learn: 0.1610939	total: 5.07s	remaining: 2m 11s
37:	learn: 0.1604299	total: 5.2s	remaining: 2m 11s
38:	learn: 0.1597023	total: 5.33s	remaining: 2m 11s
39:	learn: 0.1593197	total: 5.45s	remaining: 2m 10s
40:	learn: 0.1588813	total: 5.58s	remaining: 2m 10s
41:	learn: 0.1584508	total: 5.72s	remaining: 2m 10s
42:	learn: 0.1580801	total: 5.84s	remaining: 2m 9s
43:	learn: 0.1576136	total: 5.97s	remaining: 2m 9s
44:	learn: 0.1573872	total: 6.09s	remaining: 2m 9s
45:	learn: 0.1568505	total: 6.21s	remaining: 2m 8s
46:	learn: 0.1565716	total: 6.33s	remaining: 2m 8s
47:	learn: 0.1561914	total: 6.47s	remaining: 2m 8s
48:	learn: 0.1559473	total: 6.6s	remaining: 2m 8s
49:	learn: 0.1556032	total: 6.72s	remaining: 2m 7s
50:	learn: 0.1553512	total: 6.85s	remaining: 2m 7s
51:	learn: 0.1551879	total: 6.98s	remaining: 2m 7s
52:	learn: 0.1549848	total: 7.11s	remaining: 2m 7s
53:	learn: 0.1547982	total: 7.25s	remaining: 2m 7s
54:	learn: 0.1545869	total: 7.4s	remaining: 2m 7s
55:	learn: 0.1542203	total: 7.54s	remaining: 2m 7s
56:	learn: 0.1540034	total: 7.66s	remaining: 2m 6s
57:	learn: 0.1538354	total: 7.81s	remaining: 2m 6s
58:	learn: 0.1536554	total: 7.95s	remaining: 2m 6s
59:	learn: 0.1534990	total: 8.07s	remaining: 2m 6s
60:	learn: 0.1533261	total: 8.21s	remaining: 2m 6s
61:	learn: 0.1531914	total: 8.35s	remaining: 2m 6s
62:	learn: 0.1530276	total: 8.48s	remaining: 2m 6s
63:	learn: 0.1528961	total: 8.62s	remaining: 2m 6s
64:	learn: 0.1527300	total: 8.76s	remaining: 2m 5s
65:	learn: 0.1525305	total: 8.89s	remaining: 2m 5s
66:	learn: 0.1524047	total: 9.01s	remaining: 2m 5s
67:	learn: 0.1522907	total: 9.14s	remaining: 2m 5s
68:	learn: 0.1521345	total: 9.26s	remaining: 2m 4s
69:	learn: 0.1519218	total: 9.39s	remaining: 2m 4s
70:	learn: 0.1518166	total: 9.52s	remaining: 2m 4s
71:	learn: 0.1517247	total: 9.66s	remaining: 2m 4s
72:	learn: 0.1516090	total: 9.8s	remaining: 2m 4s
73:	learn: 0.1514658	total: 9.93s	remaining: 2m 4s
74:	learn: 0.1513508	total: 10.1s	remaining: 2m 3s
75:	learn: 0.1512797	total: 10.2s	remaining: 2m 3s
76:	learn: 0.1511880	total: 10.3s	remaining: 2m 3s
77:	learn: 0.1510657	total: 10.4s	remaining: 2m 3s
78:	learn: 0.1509710	total: 10.5s	remaining: 2m 2s
79:	learn: 0.1508304	total: 10.7s	remaining: 2m 2s
80:	learn: 0.1507596	total: 10.8s	remaining: 2m 2s
81:	learn: 0.1506965	total: 10.9s	remaining: 2m 2s
82:	learn: 0.1505988	total: 11.1s	remaining: 2m 2s
83:	learn: 0.1505395	total: 11.2s	remaining: 2m 2s
84:	learn: 0.1504635	total: 11.4s	remaining: 2m 2s
85:	learn: 0.1504048	total: 11.5s	remaining: 2m 2s
86:	learn: 0.1503496	total: 11.6s	remaining: 2m 2s
87:	learn: 0.1503013	total: 11.7s	remaining: 2m 1s
88:	learn: 0.1502143	total: 11.9s	remaining: 2m 1s
89:	learn: 0.1501812	total: 12s	remaining: 2m 1s
90:	learn: 0.1501192	total: 12.2s	remaining: 2m 1s
91:	learn: 0.1500213	total: 12.3s	remaining: 2m 1s
92:	learn: 0.1499436	total: 12.4s	remaining: 2m 1s
93:	learn: 0.1498938	total: 12.5s	remaining: 2m
94:	learn: 0.1498541	total: 12.7s	remaining: 2m
95:	learn: 0.1497993	total: 12.8s	remaining: 2m
96:	learn: 0.1497357	total: 13s	remaining: 2m
97:	learn: 0.1496826	total: 13.1s	remaining: 2m
98:	learn: 0.1496164	total: 13.2s	remaining: 2m
99:	learn: 0.1495514	total: 13.4s	remaining: 2m
100:	learn: 0.1494877	total: 13.5s	remaining: 2m
101:	learn: 0.1494061	total: 13.6s	remaining: 2m
102:	learn: 0.1493798	total: 13.8s	remaining: 2m
103:	learn: 0.1493087	total: 13.9s	remaining: 1m 59s
104:	learn: 0.1492808	total: 14s	remaining: 1m 59s
105:	learn: 0.1491580	total: 14.2s	remaining: 1m 59s
106:	learn: 0.1490775	total: 14.3s	remaining: 1m 59s
107:	learn: 0.1490125	total: 14.4s	remaining: 1m 59s
108:	learn: 0.1489589	total: 14.6s	remaining: 1m 59s
109:	learn: 0.1489200	total: 14.7s	remaining: 1m 59s
110:	learn: 0.1488293	total: 14.9s	remaining: 1m 59s
111:	learn: 0.1487722	total: 15s	remaining: 1m 58s
112:	learn: 0.1487311	total: 15.1s	remaining: 1m 58s
113:	learn: 0.1486966	total: 15.3s	remaining: 1m 58s
114:	learn: 0.1486574	total: 15.4s	remaining: 1m 58s
115:	learn: 0.1486207	total: 15.5s	remaining: 1m 58s
116:	learn: 0.1486131	total: 15.6s	remaining: 1m 57s
117:	learn: 0.1485507	total: 15.7s	remaining: 1m 57s
118:	learn: 0.1485190	total: 15.9s	remaining: 1m 57s
119:	learn: 0.1485069	total: 16s	remaining: 1m 57s
120:	learn: 0.1484332	total: 16.1s	remaining: 1m 57s
121:	learn: 0.1483584	total: 16.3s	remaining: 1m 56s
122:	learn: 0.1483117	total: 16.4s	remaining: 1m 56s
123:	learn: 0.1482813	total: 16.5s	remaining: 1m 56s
124:	learn: 0.1482400	total: 16.7s	remaining: 1m 56s
125:	learn: 0.1482086	total: 16.8s	remaining: 1m 56s
126:	learn: 0.1481173	total: 17s	remaining: 1m 56s
127:	learn: 0.1480845	total: 17.1s	remaining: 1m 56s
128:	learn: 0.1480594	total: 17.3s	remaining: 1m 56s
129:	learn: 0.1480348	total: 17.4s	remaining: 1m 56s
130:	learn: 0.1480178	total: 17.6s	remaining: 1m 56s
131:	learn: 0.1480012	total: 17.7s	remaining: 1m 56s
132:	learn: 0.1479573	total: 17.9s	remaining: 1m 56s
133:	learn: 0.1479210	total: 18s	remaining: 1m 56s
134:	learn: 0.1478779	total: 18.1s	remaining: 1m 56s
135:	learn: 0.1478469	total: 18.3s	remaining: 1m 56s
136:	learn: 0.1478357	total: 18.4s	remaining: 1m 55s
137:	learn: 0.1478115	total: 18.5s	remaining: 1m 55s
138:	learn: 0.1477610	total: 18.6s	remaining: 1m 55s
139:	learn: 0.1477409	total: 18.8s	remaining: 1m 55s
140:	learn: 0.1476568	total: 18.9s	remaining: 1m 55s
141:	learn: 0.1475905	total: 19s	remaining: 1m 54s
142:	learn: 0.1475452	total: 19.1s	remaining: 1m 54s
143:	learn: 0.1475325	total: 19.3s	remaining: 1m 54s
144:	learn: 0.1475008	total: 19.4s	remaining: 1m 54s
145:	learn: 0.1474695	total: 19.5s	remaining: 1m 54s
146:	learn: 0.1473846	total: 19.6s	remaining: 1m 54s
147:	learn: 0.1473266	total: 19.8s	remaining: 1m 53s
148:	learn: 0.1472791	total: 19.9s	remaining: 1m 53s
149:	learn: 0.1472257	total: 20s	remaining: 1m 53s
150:	learn: 0.1472041	total: 20.2s	remaining: 1m 53s
151:	learn: 0.1471775	total: 20.3s	remaining: 1m 53s
152:	learn: 0.1471378	total: 20.4s	remaining: 1m 53s
153:	learn: 0.1471241	total: 20.6s	remaining: 1m 53s
154:	learn: 0.1471088	total: 20.7s	remaining: 1m 52s
155:	learn: 0.1470730	total: 20.8s	remaining: 1m 52s
156:	learn: 0.1470274	total: 21s	remaining: 1m 52s
157:	learn: 0.1469920	total: 21.1s	remaining: 1m 52s
158:	learn: 0.1469656	total: 21.2s	remaining: 1m 52s
159:	learn: 0.1469501	total: 21.4s	remaining: 1m 52s
160:	learn: 0.1468906	total: 21.5s	remaining: 1m 51s
161:	learn: 0.1468781	total: 21.6s	remaining: 1m 51s
162:	learn: 0.1468191	total: 21.7s	remaining: 1m 51s
163:	learn: 0.1468191	total: 21.8s	remaining: 1m 51s
164:	learn: 0.1468069	total: 21.9s	remaining: 1m 50s
165:	learn: 0.1468069	total: 22s	remaining: 1m 50s
166:	learn: 0.1467794	total: 22.1s	remaining: 1m 50s
167:	learn: 0.1467532	total: 22.3s	remaining: 1m 50s
168:	learn: 0.1467359	total: 22.4s	remaining: 1m 50s
169:	learn: 0.1467052	total: 22.5s	remaining: 1m 49s
170:	learn: 0.1466997	total: 22.6s	remaining: 1m 49s
171:	learn: 0.1466494	total: 22.8s	remaining: 1m 49s
172:	learn: 0.1465657	total: 22.9s	remaining: 1m 49s
173:	learn: 0.1465031	total: 23s	remaining: 1m 49s
174:	learn: 0.1464879	total: 23.2s	remaining: 1m 49s
175:	learn: 0.1464250	total: 23.3s	remaining: 1m 49s
176:	learn: 0.1463954	total: 23.4s	remaining: 1m 48s
177:	learn: 0.1463818	total: 23.5s	remaining: 1m 48s
178:	learn: 0.1463392	total: 23.7s	remaining: 1m 48s
179:	learn: 0.1463088	total: 23.8s	remaining: 1m 48s
180:	learn: 0.1462826	total: 23.9s	remaining: 1m 48s
181:	learn: 0.1462499	total: 24.1s	remaining: 1m 48s
182:	learn: 0.1462306	total: 24.2s	remaining: 1m 48s
183:	learn: 0.1461946	total: 24.3s	remaining: 1m 47s
184:	learn: 0.1461695	total: 24.5s	remaining: 1m 47s
185:	learn: 0.1461329	total: 24.6s	remaining: 1m 47s
186:	learn: 0.1461169	total: 24.7s	remaining: 1m 47s
187:	learn: 0.1460751	total: 24.8s	remaining: 1m 47s
188:	learn: 0.1460344	total: 25s	remaining: 1m 47s
189:	learn: 0.1460299	total: 25.1s	remaining: 1m 46s
190:	learn: 0.1459722	total: 25.2s	remaining: 1m 46s
191:	learn: 0.1459540	total: 25.4s	remaining: 1m 46s
192:	learn: 0.1458934	total: 25.5s	remaining: 1m 46s
193:	learn: 0.1458853	total: 25.7s	remaining: 1m 46s
194:	learn: 0.1458266	total: 25.8s	remaining: 1m 46s
195:	learn: 0.1458057	total: 25.9s	remaining: 1m 46s
196:	learn: 0.1457796	total: 26.1s	remaining: 1m 46s
197:	learn: 0.1457533	total: 26.2s	remaining: 1m 46s
198:	learn: 0.1457427	total: 26.3s	remaining: 1m 45s
199:	learn: 0.1457271	total: 26.4s	remaining: 1m 45s
200:	learn: 0.1457140	total: 26.6s	remaining: 1m 45s
201:	learn: 0.1456814	total: 26.7s	remaining: 1m 45s
202:	learn: 0.1456468	total: 26.8s	remaining: 1m 45s
203:	learn: 0.1455962	total: 26.9s	remaining: 1m 45s
204:	learn: 0.1455437	total: 27.1s	remaining: 1m 44s
205:	learn: 0.1455046	total: 27.2s	remaining: 1m 44s
206:	learn: 0.1454492	total: 27.3s	remaining: 1m 44s
207:	learn: 0.1454211	total: 27.5s	remaining: 1m 44s
208:	learn: 0.1454092	total: 27.6s	remaining: 1m 44s
209:	learn: 0.1453767	total: 27.7s	remaining: 1m 44s
210:	learn: 0.1453402	total: 27.8s	remaining: 1m 44s
211:	learn: 0.1453296	total: 28s	remaining: 1m 43s
212:	learn: 0.1453168	total: 28.1s	remaining: 1m 43s
213:	learn: 0.1452982	total: 28.2s	remaining: 1m 43s
214:	learn: 0.1452552	total: 28.4s	remaining: 1m 43s
215:	learn: 0.1452052	total: 28.5s	remaining: 1m 43s
216:	learn: 0.1451690	total: 28.6s	remaining: 1m 43s
217:	learn: 0.1451335	total: 28.7s	remaining: 1m 43s
218:	learn: 0.1451031	total: 28.9s	remaining: 1m 42s
219:	learn: 0.1450758	total: 29s	remaining: 1m 42s
220:	learn: 0.1450437	total: 29.2s	remaining: 1m 42s
221:	learn: 0.1450304	total: 29.3s	remaining: 1m 42s
222:	learn: 0.1450166	total: 29.4s	remaining: 1m 42s
223:	learn: 0.1449920	total: 29.6s	remaining: 1m 42s
224:	learn: 0.1449811	total: 29.8s	remaining: 1m 42s
225:	learn: 0.1449567	total: 29.9s	remaining: 1m 42s
226:	learn: 0.1449433	total: 30s	remaining: 1m 42s
227:	learn: 0.1449140	total: 30.1s	remaining: 1m 42s
228:	learn: 0.1448972	total: 30.3s	remaining: 1m 42s
229:	learn: 0.1448734	total: 30.4s	remaining: 1m 41s
230:	learn: 0.1448374	total: 30.6s	remaining: 1m 41s
231:	learn: 0.1448237	total: 30.7s	remaining: 1m 41s
232:	learn: 0.1448141	total: 30.9s	remaining: 1m 41s
233:	learn: 0.1447883	total: 31s	remaining: 1m 41s
234:	learn: 0.1447428	total: 31.2s	remaining: 1m 41s
235:	learn: 0.1447157	total: 31.3s	remaining: 1m 41s
236:	learn: 0.1446988	total: 31.5s	remaining: 1m 41s
237:	learn: 0.1446744	total: 31.6s	remaining: 1m 41s
238:	learn: 0.1446207	total: 31.7s	remaining: 1m 41s
239:	learn: 0.1445930	total: 31.9s	remaining: 1m 40s
240:	learn: 0.1445371	total: 32s	remaining: 1m 40s
241:	learn: 0.1445264	total: 32.1s	remaining: 1m 40s
242:	learn: 0.1445050	total: 32.3s	remaining: 1m 40s
243:	learn: 0.1444882	total: 32.5s	remaining: 1m 40s
244:	learn: 0.1444758	total: 32.6s	remaining: 1m 40s
245:	learn: 0.1444632	total: 32.7s	remaining: 1m 40s
246:	learn: 0.1444581	total: 32.9s	remaining: 1m 40s
247:	learn: 0.1444195	total: 33s	remaining: 1m 40s
248:	learn: 0.1443827	total: 33.2s	remaining: 1m 40s
249:	learn: 0.1443313	total: 33.3s	remaining: 1m 39s
250:	learn: 0.1442931	total: 33.5s	remaining: 1m 39s
251:	learn: 0.1442625	total: 33.6s	remaining: 1m 39s
252:	learn: 0.1442449	total: 33.7s	remaining: 1m 39s
253:	learn: 0.1442311	total: 33.9s	remaining: 1m 39s
254:	learn: 0.1442209	total: 34s	remaining: 1m 39s
255:	learn: 0.1442082	total: 34.1s	remaining: 1m 39s
256:	learn: 0.1441967	total: 34.3s	remaining: 1m 39s
257:	learn: 0.1441794	total: 34.4s	remaining: 1m 38s
258:	learn: 0.1441508	total: 34.5s	remaining: 1m 38s
259:	learn: 0.1441420	total: 34.7s	remaining: 1m 38s
260:	learn: 0.1441319	total: 34.8s	remaining: 1m 38s
261:	learn: 0.1440862	total: 34.9s	remaining: 1m 38s
262:	learn: 0.1440428	total: 35.1s	remaining: 1m 38s
263:	learn: 0.1440132	total: 35.2s	remaining: 1m 38s
264:	learn: 0.1440002	total: 35.3s	remaining: 1m 37s
265:	learn: 0.1439917	total: 35.4s	remaining: 1m 37s
266:	learn: 0.1439589	total: 35.6s	remaining: 1m 37s
267:	learn: 0.1439393	total: 35.7s	remaining: 1m 37s
268:	learn: 0.1439285	total: 35.8s	remaining: 1m 37s
269:	learn: 0.1439179	total: 35.9s	remaining: 1m 37s
270:	learn: 0.1438881	total: 36.1s	remaining: 1m 37s
271:	learn: 0.1438717	total: 36.2s	remaining: 1m 36s
272:	learn: 0.1438484	total: 36.3s	remaining: 1m 36s
273:	learn: 0.1438325	total: 36.5s	remaining: 1m 36s
274:	learn: 0.1437787	total: 36.6s	remaining: 1m 36s
275:	learn: 0.1437499	total: 36.7s	remaining: 1m 36s
276:	learn: 0.1437159	total: 36.9s	remaining: 1m 36s
277:	learn: 0.1436700	total: 37s	remaining: 1m 36s
278:	learn: 0.1436235	total: 37.1s	remaining: 1m 35s
279:	learn: 0.1435816	total: 37.3s	remaining: 1m 35s
280:	learn: 0.1435301	total: 37.4s	remaining: 1m 35s
281:	learn: 0.1435265	total: 37.6s	remaining: 1m 35s
282:	learn: 0.1435098	total: 37.7s	remaining: 1m 35s
283:	learn: 0.1434823	total: 37.8s	remaining: 1m 35s
284:	learn: 0.1434721	total: 38s	remaining: 1m 35s
285:	learn: 0.1434559	total: 38.1s	remaining: 1m 35s
286:	learn: 0.1434483	total: 38.2s	remaining: 1m 34s
287:	learn: 0.1434359	total: 38.4s	remaining: 1m 34s
288:	learn: 0.1433819	total: 38.5s	remaining: 1m 34s
289:	learn: 0.1433539	total: 38.6s	remaining: 1m 34s
290:	learn: 0.1433419	total: 38.8s	remaining: 1m 34s
291:	learn: 0.1433155	total: 38.9s	remaining: 1m 34s
292:	learn: 0.1432886	total: 39s	remaining: 1m 34s
293:	learn: 0.1432752	total: 39.2s	remaining: 1m 34s
294:	learn: 0.1432470	total: 39.3s	remaining: 1m 33s
295:	learn: 0.1432430	total: 39.4s	remaining: 1m 33s
296:	learn: 0.1432077	total: 39.5s	remaining: 1m 33s
297:	learn: 0.1431931	total: 39.7s	remaining: 1m 33s
298:	learn: 0.1431634	total: 39.8s	remaining: 1m 33s
299:	learn: 0.1431492	total: 39.9s	remaining: 1m 33s
300:	learn: 0.1431388	total: 40s	remaining: 1m 33s
301:	learn: 0.1431222	total: 40.2s	remaining: 1m 32s
302:	learn: 0.1430999	total: 40.3s	remaining: 1m 32s
303:	learn: 0.1430978	total: 40.5s	remaining: 1m 32s
304:	learn: 0.1430772	total: 40.6s	remaining: 1m 32s
305:	learn: 0.1430654	total: 40.7s	remaining: 1m 32s
306:	learn: 0.1430510	total: 40.9s	remaining: 1m 32s
307:	learn: 0.1430408	total: 41s	remaining: 1m 32s
308:	learn: 0.1430122	total: 41.2s	remaining: 1m 32s
309:	learn: 0.1430053	total: 41.3s	remaining: 1m 31s
310:	learn: 0.1429965	total: 41.4s	remaining: 1m 31s
311:	learn: 0.1429554	total: 41.5s	remaining: 1m 31s
312:	learn: 0.1429150	total: 41.7s	remaining: 1m 31s
313:	learn: 0.1429111	total: 41.8s	remaining: 1m 31s
314:	learn: 0.1428792	total: 42s	remaining: 1m 31s
315:	learn: 0.1428627	total: 42.1s	remaining: 1m 31s
316:	learn: 0.1428170	total: 42.2s	remaining: 1m 31s
317:	learn: 0.1427862	total: 42.4s	remaining: 1m 30s
318:	learn: 0.1427750	total: 42.5s	remaining: 1m 30s
319:	learn: 0.1427677	total: 42.6s	remaining: 1m 30s
320:	learn: 0.1427415	total: 42.8s	remaining: 1m 30s
321:	learn: 0.1427022	total: 42.9s	remaining: 1m 30s
322:	learn: 0.1426648	total: 43.1s	remaining: 1m 30s
323:	learn: 0.1426563	total: 43.2s	remaining: 1m 30s
324:	learn: 0.1426135	total: 43.3s	remaining: 1m 29s
325:	learn: 0.1426033	total: 43.4s	remaining: 1m 29s
326:	learn: 0.1425963	total: 43.6s	remaining: 1m 29s
327:	learn: 0.1425909	total: 43.7s	remaining: 1m 29s
328:	learn: 0.1425668	total: 43.8s	remaining: 1m 29s
329:	learn: 0.1425506	total: 44s	remaining: 1m 29s
330:	learn: 0.1425092	total: 44.1s	remaining: 1m 29s
331:	learn: 0.1424883	total: 44.2s	remaining: 1m 28s
332:	learn: 0.1424729	total: 44.4s	remaining: 1m 28s
333:	learn: 0.1424593	total: 44.5s	remaining: 1m 28s
334:	learn: 0.1424552	total: 44.6s	remaining: 1m 28s
335:	learn: 0.1424225	total: 44.8s	remaining: 1m 28s
336:	learn: 0.1424039	total: 44.9s	remaining: 1m 28s
337:	learn: 0.1423607	total: 45.1s	remaining: 1m 28s
338:	learn: 0.1423394	total: 45.2s	remaining: 1m 28s
339:	learn: 0.1423239	total: 45.3s	remaining: 1m 28s
340:	learn: 0.1423153	total: 45.5s	remaining: 1m 27s
341:	learn: 0.1423081	total: 45.6s	remaining: 1m 27s
342:	learn: 0.1422711	total: 45.7s	remaining: 1m 27s
343:	learn: 0.1422611	total: 45.9s	remaining: 1m 27s
344:	learn: 0.1422460	total: 46s	remaining: 1m 27s
345:	learn: 0.1422346	total: 46.2s	remaining: 1m 27s
346:	learn: 0.1422107	total: 46.3s	remaining: 1m 27s
347:	learn: 0.1421794	total: 46.5s	remaining: 1m 27s
348:	learn: 0.1421393	total: 46.6s	remaining: 1m 26s
349:	learn: 0.1421184	total: 46.7s	remaining: 1m 26s
350:	learn: 0.1420935	total: 46.9s	remaining: 1m 26s
351:	learn: 0.1420574	total: 47s	remaining: 1m 26s
352:	learn: 0.1420186	total: 47.1s	remaining: 1m 26s
353:	learn: 0.1420041	total: 47.3s	remaining: 1m 26s
354:	learn: 0.1419997	total: 47.4s	remaining: 1m 26s
355:	learn: 0.1419629	total: 47.6s	remaining: 1m 26s
356:	learn: 0.1419419	total: 47.7s	remaining: 1m 25s
357:	learn: 0.1419293	total: 47.9s	remaining: 1m 25s
358:	learn: 0.1419143	total: 48s	remaining: 1m 25s
359:	learn: 0.1418929	total: 48.1s	remaining: 1m 25s
360:	learn: 0.1418803	total: 48.3s	remaining: 1m 25s
361:	learn: 0.1418535	total: 48.4s	remaining: 1m 25s
362:	learn: 0.1418336	total: 48.6s	remaining: 1m 25s
363:	learn: 0.1418269	total: 48.7s	remaining: 1m 25s
364:	learn: 0.1417957	total: 48.9s	remaining: 1m 25s
365:	learn: 0.1417821	total: 49s	remaining: 1m 24s
366:	learn: 0.1417396	total: 49.2s	remaining: 1m 24s
367:	learn: 0.1417310	total: 49.3s	remaining: 1m 24s
368:	learn: 0.1417132	total: 49.4s	remaining: 1m 24s
369:	learn: 0.1417001	total: 49.6s	remaining: 1m 24s
370:	learn: 0.1416931	total: 49.7s	remaining: 1m 24s
371:	learn: 0.1416704	total: 49.8s	remaining: 1m 24s
372:	learn: 0.1416403	total: 50s	remaining: 1m 24s
373:	learn: 0.1416325	total: 50.1s	remaining: 1m 23s
374:	learn: 0.1416164	total: 50.2s	remaining: 1m 23s
375:	learn: 0.1416023	total: 50.4s	remaining: 1m 23s
376:	learn: 0.1415746	total: 50.5s	remaining: 1m 23s
377:	learn: 0.1415385	total: 50.6s	remaining: 1m 23s
378:	learn: 0.1415351	total: 50.8s	remaining: 1m 23s
379:	learn: 0.1414973	total: 50.9s	remaining: 1m 23s
380:	learn: 0.1414690	total: 51s	remaining: 1m 22s
381:	learn: 0.1414599	total: 51.2s	remaining: 1m 22s

In [17]:
base_pred = cb_model.predict(X_test)

In [25]:
base_prec = precision_score(y_test,base_pred)
base_rec = recall_score(y_test,base_pred)
base_f1 = f1_score(y_test,base_pred)
base_roc_auc = roc_auc_score(y_test,base_pred)
conf_matrix = confusion_matrix(y_test,base_pred)
report = classification_report(y_test,base_pred)

In [28]:
print('precision =',base_prec)
print('recall =',base_rec)
print('f1 =',base_f1)
print('roc_auc =',base_roc_auc)
display(conf_matrix)
print(report)
#Видим, что базовая модель выдаёт вполне неплохие показатели всех метрик. Только в конкретном случае, хотелось бы 
#видеть recall больше для полного охвата людей с депрессией

precision = 0.8444087532623971
recall = 0.8160651920838184
f1 = 0.8299950666008881
roc_auc = 0.8911745085103682

array([[22211,   775],
       [  948,  4206]], dtype=int64)

              precision    recall  f1-score   support

           0       0.96      0.97      0.96     22986
           1       0.84      0.82      0.83      5154

    accuracy                           0.94     28140
   macro avg       0.90      0.89      0.90     28140
weighted avg       0.94      0.94      0.94     28140

In [33]:
features = cb_model.feature_names_
importance = cb_model.feature_importances_

for f,i in zip(features,importance):
    print(f,':',i)

Gender : 0.3747670689597349
Age : 29.131586595178067
City : 2.861981639920748
Working Professional or Student : 0.01642510447791969
Profession : 3.49113312226932
Academic Pressure : 6.303700409590826
Work Pressure : 8.018194365330627
CGPA : 1.2963755745924757
Study Satisfaction : 1.0432227552522815
Job Satisfaction : 7.796959367074027
Sleep Duration : 2.894196686353519
Dietary Habits : 3.9824287077569367
Degree : 2.7591506730210655
Have you ever had suicidal thoughts ? : 16.476667021098784
Work/Study Hours : 5.546103268100959
Financial Stress : 7.521986509097306
Family History of Mental Illness : 0.4851211319253858

In [34]:
#Наша модель обучалась 2 минуты 15 секунд. Понятно, что поиск гиперпараметров по сетке займёт
#очень много времени. Можно использовать либо RandomSearch, но тогда мы можем упустить лучшую вариацию гиперпараметров
#Поэтому будем использовать библиотеку optuna основанную на байесовской оптимизации
#Так же благодаря использованию optuna мы можем позволиить себе расширить диапазон гиперпараметров

In [3]:
categorical_features = [0,2,3,4,10,11,12,13,16]

In [8]:
#В силу несбалансированности классов используем балансировку
#Так как у нас много категориальных перемнных, будем варьировать параметр, отвечающий за кодировку
#Остальные варьируемы параметры классические(iterations для макс количества деревьев,learning_rate для шага градиента)
#depth для глубины деревьев и l2_leaf_reg для настройки регуляризации(борьбы с переобучением)
#Также протестируем разые метрики используемые в процессе обучения, так для нас очень важен recall в силу задачи
def objective(trial):
    params={'iterations' : trial.suggest_int('iterations',400,1600,step=100),
    'learning_rate' : trial.suggest_float('learning_rate',0.01,0.1,log=True),
    'depth' : trial.suggest_int('depth',4,10),
    'l2_leaf_reg' : trial.suggest_int('l2_leaf_reg',1,7),
    'eval_metric' : trial.suggest_categorical('eval_metric', ['AUC', 'Recall', 'Logloss'])}
    
    cbc = CatBoostClassifier(**params,auto_class_weights='Balanced',verbose=0,random_seed=42,cat_features=categorical_features)
    return cross_val_score(cbc, X_train, y_train, cv=3, scoring='recall').mean()

study = optuna.create_study(direction='maximize')
study.optimize(objective,n_trials=30)

best_params = study.best_params

[I 2025-11-28 15:10:25,508] A new study created in memory with name: no-name-d1101f34-f12c-4777-a02d-96858836bba4
[I 2025-11-28 15:12:26,638] Trial 0 finished with value: 0.9293590104105248 and parameters: {'iterations': 500, 'learning_rate': 0.015751454707678976, 'depth': 5, 'l2_leaf_reg': 1, 'eval_metric': 'Logloss'}. Best is trial 0 with value: 0.9293590104105248.
[I 2025-11-28 15:13:58,372] Trial 1 finished with value: 0.9288200829265406 and parameters: {'iterations': 400, 'learning_rate': 0.08324074892423197, 'depth': 4, 'l2_leaf_reg': 5, 'eval_metric': 'Recall'}. Best is trial 0 with value: 0.9293590104105248.
[I 2025-11-28 15:43:36,930] Trial 2 finished with value: 0.9296529119535079 and parameters: {'iterations': 800, 'learning_rate': 0.014309558343130706, 'depth': 6, 'l2_leaf_reg': 2, 'eval_metric': 'Recall'}. Best is trial 2 with value: 0.9296529119535079.
[I 2025-11-28 15:47:53,421] Trial 3 finished with value: 0.9291140420633984 and parameters: {'iterations': 1000, 'learning_rate': 0.01888905318917998, 'depth': 5, 'l2_leaf_reg': 1, 'eval_metric': 'Logloss'}. Best is trial 2 with value: 0.9296529119535079.
[I 2025-11-28 15:55:08,908] Trial 4 finished with value: 0.9118212435871019 and parameters: {'iterations': 1200, 'learning_rate': 0.060859731802345454, 'depth': 7, 'l2_leaf_reg': 2, 'eval_metric': 'Recall'}. Best is trial 2 with value: 0.9296529119535079.
[I 2025-11-28 18:44:03,770] Trial 5 finished with value: 0.926223686258519 and parameters: {'iterations': 600, 'learning_rate': 0.02937347752939159, 'depth': 7, 'l2_leaf_reg': 1, 'eval_metric': 'Logloss'}. Best is trial 2 with value: 0.9296529119535079.
[I 2025-11-28 18:46:58,213] Trial 6 finished with value: 0.9244601330159335 and parameters: {'iterations': 400, 'learning_rate': 0.010711104740326554, 'depth': 10, 'l2_leaf_reg': 7, 'eval_metric': 'AUC'}. Best is trial 2 with value: 0.9296529119535079.
[I 2025-11-28 18:53:43,879] Trial 7 finished with value: 0.9282322510436369 and parameters: {'iterations': 1600, 'learning_rate': 0.01171324299423924, 'depth': 6, 'l2_leaf_reg': 7, 'eval_metric': 'Logloss'}. Best is trial 2 with value: 0.9296529119535079.
[I 2025-11-28 18:57:59,582] Trial 8 finished with value: 0.912849898987543 and parameters: {'iterations': 800, 'learning_rate': 0.06242873732703307, 'depth': 8, 'l2_leaf_reg': 6, 'eval_metric': 'Logloss'}. Best is trial 2 with value: 0.9296529119535079.
[I 2025-11-28 19:11:53,410] Trial 9 finished with value: 0.8959979816226585 and parameters: {'iterations': 1500, 'learning_rate': 0.03020849580075241, 'depth': 9, 'l2_leaf_reg': 1, 'eval_metric': 'Recall'}. Best is trial 2 with value: 0.9296529119535079.
[I 2025-11-28 19:19:03,995] Trial 10 finished with value: 0.9306326917519668 and parameters: {'iterations': 1200, 'learning_rate': 0.01830471873761281, 'depth': 4, 'l2_leaf_reg': 3, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 19:28:01,809] Trial 11 finished with value: 0.9295549447725135 and parameters: {'iterations': 1200, 'learning_rate': 0.01963114878748447, 'depth': 4, 'l2_leaf_reg': 3, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 19:37:02,474] Trial 12 finished with value: 0.9284282358002661 and parameters: {'iterations': 900, 'learning_rate': 0.021748006347754322, 'depth': 6, 'l2_leaf_reg': 3, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 19:48:04,355] Trial 13 finished with value: 0.9293590104105248 and parameters: {'iterations': 1300, 'learning_rate': 0.014611353460738554, 'depth': 5, 'l2_leaf_reg': 4, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 19:54:49,346] Trial 14 finished with value: 0.9261257766713995 and parameters: {'iterations': 700, 'learning_rate': 0.042411344025350496, 'depth': 6, 'l2_leaf_reg': 3, 'eval_metric': 'Recall'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 20:02:30,959] Trial 15 finished with value: 0.9296529047542735 and parameters: {'iterations': 1100, 'learning_rate': 0.024247981998938614, 'depth': 4, 'l2_leaf_reg': 4, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 20:18:50,237] Trial 16 finished with value: 0.9228924925376337 and parameters: {'iterations': 1400, 'learning_rate': 0.014082662211493265, 'depth': 8, 'l2_leaf_reg': 2, 'eval_metric': 'Recall'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 20:26:12,867] Trial 17 finished with value: 0.927644368766093 and parameters: {'iterations': 900, 'learning_rate': 0.04004274769679159, 'depth': 5, 'l2_leaf_reg': 2, 'eval_metric': 'Recall'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 20:35:29,132] Trial 18 finished with value: 0.9294079508056159 and parameters: {'iterations': 1000, 'learning_rate': 0.012471599559358953, 'depth': 6, 'l2_leaf_reg': 5, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 20:40:25,587] Trial 19 finished with value: 0.9298978803006342 and parameters: {'iterations': 700, 'learning_rate': 0.018060187626734385, 'depth': 4, 'l2_leaf_reg': 3, 'eval_metric': 'Recall'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 20:44:42,411] Trial 20 finished with value: 0.9298489327063089 and parameters: {'iterations': 600, 'learning_rate': 0.02416064498321352, 'depth': 4, 'l2_leaf_reg': 5, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 20:49:00,666] Trial 21 finished with value: 0.9300448598690632 and parameters: {'iterations': 600, 'learning_rate': 0.02488084622793632, 'depth': 4, 'l2_leaf_reg': 5, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 20:53:18,242] Trial 22 finished with value: 0.9290160964801072 and parameters: {'iterations': 600, 'learning_rate': 0.017467267286977423, 'depth': 4, 'l2_leaf_reg': 4, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 20:58:45,431] Trial 23 finished with value: 0.9296529047542735 and parameters: {'iterations': 700, 'learning_rate': 0.02635454672825003, 'depth': 5, 'l2_leaf_reg': 3, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 21:00:52,016] Trial 24 finished with value: 0.9298979018983373 and parameters: {'iterations': 500, 'learning_rate': 0.040241565800441526, 'depth': 4, 'l2_leaf_reg': 6, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 21:03:19,612] Trial 25 finished with value: 0.9292120740375021 and parameters: {'iterations': 500, 'learning_rate': 0.0379689716581229, 'depth': 5, 'l2_leaf_reg': 6, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 21:07:56,094] Trial 26 finished with value: 0.9283302686192717 and parameters: {'iterations': 1100, 'learning_rate': 0.0492384424989575, 'depth': 4, 'l2_leaf_reg': 6, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 21:10:23,511] Trial 27 finished with value: 0.9290650656721358 and parameters: {'iterations': 500, 'learning_rate': 0.03539314748530645, 'depth': 5, 'l2_leaf_reg': 5, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 21:15:52,127] Trial 28 finished with value: 0.9276934099504649 and parameters: {'iterations': 1300, 'learning_rate': 0.049556871844523766, 'depth': 4, 'l2_leaf_reg': 6, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.
[I 2025-11-28 21:17:48,447] Trial 29 finished with value: 0.9298978515036969 and parameters: {'iterations': 400, 'learning_rate': 0.029814612432399346, 'depth': 5, 'l2_leaf_reg': 7, 'eval_metric': 'AUC'}. Best is trial 10 with value: 0.9306326917519668.

In [8]:
best_params = {'iterations': 1200,
 'learning_rate': 0.01830471873761281,
 'depth': 4,
 'l2_leaf_reg': 3,
 'eval_metric': 'AUC'}

In [9]:
cb_model = CatBoostClassifier(**best_params,auto_class_weights='Balanced',verbose=0,random_seed=42,cat_features=categorical_features)

In [12]:
cb_model.fit(X_train,y_train)

In [21]:
final_pred = cb_model.predict(X_test)

In [25]:
final_prec = precision_score(y_test,final_pred)
final_rec = recall_score(y_test,final_pred)
final_f1 = f1_score(y_test,final_pred)
final_roc_auc = roc_auc_score(y_test,final_pred)
conf_matrix = confusion_matrix(y_test,final_pred)
report = classification_report(y_test,final_pred)

In [27]:
print('precision =',final_prec)
print('recall =',final_rec)
print('f1 =',final_f1)
print('roc_auc =',final_roc_auc)
display(conf_matrix)
print(report)

precision = 0.7096063454759107
recall = 0.9373302289483896
f1 = 0.8077244607925096
roc_auc = 0.9256606769905091

array([[21009,  1977],
       [  323,  4831]], dtype=int64)

              precision    recall  f1-score   support

           0       0.98      0.91      0.95     22986
           1       0.71      0.94      0.81      5154

    accuracy                           0.92     28140
   macro avg       0.85      0.93      0.88     28140
weighted avg       0.93      0.92      0.92     28140

In [33]:
test_data = pd.read_csv('clear_test.csv').drop('Unnamed: 0',axis=1)
test_data
test = pd.read_csv('test.csv')

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93795,234495,Zoya,Female,49.0,Jaipur,Working Professional,Pilot,NaN,3.0,NaN,NaN,5.0,Less than 5 hours,Moderate,BSc,Yes,2.0,2.0,Yes
93796,234496,Shlok,Male,29.0,Ahmedabad,Working Professional,Pilot,NaN,5.0,NaN,NaN,1.0,7-8 hours,Moderate,BE,Yes,11.0,3.0,Yes
93797,234497,Rishi,Male,24.0,Visakhapatnam,Student,NaN,1.0,NaN,7.51,4.0,NaN,7-8 hours,Moderate,B.Tech,No,7.0,1.0,No
93798,234498,Eshita,Female,23.0,Kalyan,Working Professional,Marketing Manager,NaN,4.0,NaN,NaN,2.0,5-6 hours,Healthy,BA,Yes,7.0,5.0,Yes
93799,234499,Gauri,Female,43.0,Varanasi,Working Professional,Educational Consultant,NaN,5.0,NaN,NaN,2.0,More than 8 hours,Healthy,B.Ed,No,11.0,2.0,No

In [32]:
test_pred  = cb_model.predict(test_data)

In [35]:
submission = pd.DataFrame({
    'id': test['id'],  
    'depression': test_pred
})
submission.to_csv('submission.csv', index=False)
submission

           id  depression
0      140700           0
1      140701           0
2      140702           0
3      140703           1
4      140704           0
...       ...         ...
93795  234495           0
93796  234496           1
93797  234497           0
93798  234498           1
93799  234499           0

[93800 rows x 2 columns]